from google import genai
from google.genai import types
import os

api_key = "AIzaSyCXJ7nKNtiD5MfgAKryuGp957jJJGPXNOQ"
client = genai.Client(api_key=api_key)

models_to_test = [
    'imagen-4.0-fast-generate-001',
    'gemini-3.1-flash-image-preview'
]

for model in models_to_test:
    print(f"Testing model: {model}")
    try:
        if "imagen" in model:
            response = client.models.generate_images(
                model=model,
                prompt="A cute cat on a moon",
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                )
            )
            if response.generated_images:
                print(f"  SUCCESS: Generated image with {model}")
            else:
                print(f"  FAILED: No images generated by {model}")
        else:
            # For gemini image models, try generate_content
            response = client.models.generate_content(
                model=model,
                contents="Génère une image d'un chat sur la lune."
            )
            # Check if there is an image part in the response
            has_image = False
            for part in response.candidates[0].content.parts:
                if part.inline_data or part.file_data:
                    has_image = True
                    break
            if has_image:
                print(f"  SUCCESS: Generated image (inline) with {model}")
            else:
                print(f"  FAILED: No image part in response from {model}")
                print(f"  Response text: {response.text}")
                
    except Exception as e:
        print(f"  ERROR with {model}: {e}")
