
import os
import asyncio
import uuid
import logging
import json
import io
from typing import List
import httpx
from pathlib import Path

from google import genai
from google.genai import types
from PIL import Image, ImageDraw, ImageFont
from fastapi import HTTPException

from core.config import settings
from core.firebase_client import firebase_storage

logger = logging.getLogger(__name__)

DEFAULT_FONT_PATH = Path(__file__).resolve().parents[2] / "core" / "assets" / "fonts" / "Roboto-Regular.ttf"
if not DEFAULT_FONT_PATH.exists():
    logger.warning(f"Default font not found at {DEFAULT_FONT_PATH}. Text rendering might fail.")

class ImageGenerationError(Exception):
    pass

class GraphicDesignerAgent:
    def __init__(self):
        if settings.LLM_PROVIDER == "vertexai":
            self.client = genai.Client(vertexai=True, project=settings.GOOGLE_CLOUD_PROJECT, location="us-central1")
        else:
            self.client = genai.Client(api_key=settings.GEMINI_API_KEY)
        self.composition_model = settings.GEMINI_PRO_MODEL or "gemini-2.5-pro"
        self.image_gen_models = ["imagen-4.0-ultra-generate-001", "imagen-3.0-generate-001"]

    def _normalize_format(self, img_format) -> str:
        if isinstance(img_format, str):
            return img_format
        if isinstance(img_format, dict):
            width = img_format.get("width") or img_format.get("w")
            height = img_format.get("height") or img_format.get("h")
            ratio = img_format.get("ratio") or img_format.get("aspect_ratio")
            if width and height:
                return f"{width}x{height}"
            if isinstance(ratio, str) and ratio:
                return ratio
        return "1080x1350"

    async def _parse_brief_to_composition_json(self, brief: str, img_format: str) -> dict:
        prompt = f"""
        You are an expert creative director AI. Your task is to interpret a user's creative brief and translate it into a structured JSON object that can be used to generate a visual.
        The user wants a visual of format {img_format}.
        The user's brief is: "{brief}"
        Analyze the brief to determine the following:
        1.  **Background**: Should the background be generated by an AI (like Imagen), or is the user providing a URL to an existing image? If it needs to be generated, create a detailed, professional, English prompt for the image generation model. If it's a solid color, specify it.
        2.  **Elements**: Identify all text elements (titles, subtitles, body text) the user wants on the image. For each text element, define its content, suggest a suitable font (e.g., "Roboto", "Montserrat", "Playfair Display"), a font size (as an integer), a color (hex code, e.g., "#FFFFFF"), and a position (e.g., {{"x": "center", "y": 100}} or {{"x": 50, "y": "center"}}).
        **Output Format**: You MUST respond with ONLY a valid JSON object. Do not include any other text or explanations.
        """
        response = await self.client.aio.models.generate_content(
            model=self.composition_model,
            contents=prompt,
            config={"response_mime_type": "application/json"}
        )
        try:
            return json.loads(response.text)
        except (json.JSONDecodeError, TypeError) as e:
            logger.error(f"""Failed to parse composition JSON from LLM: {e}
LLM Response: {response.text}""")
            raise ImageGenerationError("Failed to understand the creative brief. Could not generate a composition plan.")

    async def _get_base_image(self, composition: dict, request) -> (Image.Image, str):
        bg_info = composition.get("background", {})
        bg_type = str(bg_info.get("type") or "").strip().lower()
        normalized_format = self._normalize_format(composition.get("format", request.format))
        aspect_ratio = self._get_aspect_ratio(normalized_format)
        
        if bg_type in {"generated", "generate", "ai", "imagen"}:
            prompt = bg_info.get("prompt", "A beautiful, abstract background.")
            image_bytes, _ = await self._generate_background_image(prompt, aspect_ratio)
            image = Image.open(io.BytesIO(image_bytes))
            url = self._upload_image_to_firebase(image_bytes, request.project_id, "bg")
            return image, url
        elif bg_type in {"uploaded", "upload", "image_url", "url"}:
            url = bg_info.get("url")
            if not url:
                raise ImageGenerationError("Background type is 'uploaded' but no URL was provided.")
            async with httpx.AsyncClient() as client:
                response = await client.get(url)
                response.raise_for_status()
                image = Image.open(io.BytesIO(response.content))
                return image, url
        elif bg_type in {"solid_color", "solid", "color"}:
            color = bg_info.get("color", "#FFFFFF")
            width, height = map(int, normalized_format.split('x'))
            image = Image.new("RGB", (width, height), color)
            return image, None
        else:
            raise ImageGenerationError(f"Unsupported background type: {bg_type}")

    def _upload_image_to_firebase(self, image_bytes: bytes, project_id: str, prefix: str) -> str:
        try:
            user_id = "user_placeholder"
            file_uuid = str(uuid.uuid4())[:8]
            storage_path = f"users/{user_id}/content_studio/{project_id}/{prefix}_{file_uuid}.png"
            public_url = firebase_storage.upload_file(
                bucket_name=settings.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
                path=storage_path, 
                file_bytes=image_bytes, 
                content_type="image/png",
            )
            return public_url
        except Exception as e:
            logger.error(f"[Firebase] Failed to upload image: {e}")
            raise ImageGenerationError(f"Image created but failed to save. Details: {e}")

    def _draw_elements_on_image(self, image: Image.Image, elements: list) -> Image.Image:
        if not elements:
            return image
        
        logger.info("Beginning to draw elements on image.")
        try:
            final_image = image.convert("RGBA")
            draw = ImageDraw.Draw(final_image)

            for element in elements:
                if element.get("type") == "text":
                    try:
                        font = ImageFont.truetype(str(DEFAULT_FONT_PATH), element.get("size", 50))
                    except IOError:
                        logger.warning(f"Could not load font {DEFAULT_FONT_PATH}. Using default font.")
                        font = ImageFont.load_default()
                    
                    content = element.get("content", "")
                    text_pos = element.get("position", {})
                    text_color = element.get("color", "#000000")
                    
                    bbox = draw.textbbox((0, 0), content, font=font)
                    text_width = bbox[2] - bbox[0]
                    text_height = bbox[3] - bbox[1]
                    
                    x = text_pos.get("x", "center")
                    y = text_pos.get("y", "center")

                    try:
                        x_pos = (final_image.width - text_width) / 2 if str(x).lower() == "center" else float(x)
                    except (ValueError, TypeError):
                        x_pos = (final_image.width - text_width) / 2

                    try:
                        y_pos = (final_image.height - text_height) / 2 if str(y).lower() == "center" else float(y)
                    except (ValueError, TypeError):
                        y_pos = (final_image.height - text_height) / 2

                    draw.text((x_pos, y_pos), content, font=font, fill=text_color)

            logger.info("Successfully drew elements on image.")
            return final_image
        except Exception as e:
            logger.error(f"[Pillow] Failed during element drawing phase: {e}")
            return image

    async def generate(self, request) -> dict:
        """ARMOR-PLATED visual generation with graceful degradation."""
        try:
            composition = await self._parse_brief_to_composition_json(request.brief, request.format)
            logger.info(f"Successfully parsed brief into composition: {composition}")

            base_image, fallback_url = await self._get_base_image(composition, request)
            logger.info(f"Successfully loaded base image. Fallback URL: {fallback_url}")

            composed_image = self._draw_elements_on_image(base_image, composition.get("elements", []))

            if composed_image is not base_image:
                logger.info("Composition is different from base. Uploading new version.")
                try:
                    img_byte_arr = io.BytesIO()
                    composed_image.save(img_byte_arr, format='PNG')
                    composed_image_bytes = img_byte_arr.getvalue()
                    final_url = self._upload_image_to_firebase(composed_image_bytes, request.project_id, "composed")
                    logger.info(f"Successfully uploaded composed image. Final URL: {final_url}")
                    return {"image_url": final_url, "layers": composition.get("elements", [])}
                except Exception as e:
                    logger.error(f"Failed to upload composed image: {e}. Reverting to fallback URL if available.")
            
            if fallback_url:
                logger.warning("Returning fallback URL due to composition/upload failure.")
                return {"image_url": fallback_url, "layers": []} # No layers since composition failed
            else:
                raise ImageGenerationError("Image composition failed and no fallback URL was available (e.g., solid color background).")

        except ImageGenerationError as e:
            logger.error(f"[TKT-101] Gracefully handled image generation failure: {e}")
            raise HTTPException(status_code=500, detail=str(e))
        except Exception as e:
            logger.error(f"[TKT-101] An unexpected critical error occurred: {e}")
            raise HTTPException(status_code=500, detail="An unexpected error occurred during image generation.")

    async def _generate_background_image(self, prompt: str, aspect_ratio: str) -> (bytes, str):
        raw_bytes = None
        applied_model = None
        last_error = "No models could be reached."

        for model_name in self.image_gen_models:
            try:
                def _call_imagen():
                    return self.client.models.generate_images(
                        model=model_name, 
                        prompt=prompt,
                        config=types.GenerateImagesConfig(
                            number_of_images=1,
                            output_mime_type="image/jpeg",
                            aspect_ratio=aspect_ratio,
                        ),
                    )
                
                res = await asyncio.wait_for(asyncio.to_thread(_call_imagen), timeout=90)
                if res and res.generated_images:
                    raw_bytes = res.generated_images[0].image.image_bytes
                    applied_model = model_name
                    logger.info(f"[GraphicDesignerAgent] Image generated with {model_name}.")
                    return raw_bytes, applied_model
            except Exception as e:
                last_error = str(e)
                logger.warning(f"[GraphicDesignerAgent] Model {model_name} failed: {e}")
                continue
        
        raise ImageGenerationError(f"All image generation models failed. Last error: {last_error}")

    def _get_aspect_ratio(self, img_format: str) -> str:
        try:
            width, height = map(int, img_format.split('x'))
            ratio = width / height if height else 1
            if abs(ratio - 1) < 0.05:
                return "1:1"
            if ratio >= 1.7:
                return "16:9"
            if ratio >= 1.2:
                return "4:3"
            if ratio <= 0.62:
                return "9:16"
            if ratio <= 0.86:
                return "3:4"
            return "1:1"
        except (ValueError, IndexError):
            return "16:9"






